function verificarRepetidas(arrayPalabras) {
    // Convertir todas las palabras a minúsculas para ignorar las diferencias de mayúsculas y minúsculas
    const palabrasEnMinusculas = arrayPalabras.map(palabra => palabra.toLowerCase());

    // Crear un objeto para almacenar las palabras y su frecuencia
    const frecuenciaPalabras = {};

    // Encontrar la frecuencia de cada palabra
    palabrasEnMinusculas.forEach(palabra => {
        if (frecuenciaPalabras[palabra]) {
            frecuenciaPalabras[palabra]++;
        } else {
            frecuenciaPalabras[palabra] = 1;
        }
    });

    // Filtrar las palabras que tienen frecuencia mayor que 1 (repetidas)
    const palabrasRepetidas = Object.keys(frecuenciaPalabras).filter(palabra => frecuenciaPalabras[palabra] > 1);

    if (palabrasRepetidas.length === 0) {
        console.log("No hay palabras repetidas.");
    } else {
        console.log("Palabras repetidas:", palabrasRepetidas);
    }
}

// Ejemplo de uso
const palabras = [
    "nombre",
    "curp",
    "fecha",
    "edad",
    "sexo",
    "Estadocivil",
    "Poblacion_indigen",
    "Raza",
    "Escolaridad",
    "unidad_referencia",
    "Alcaldia_municipio",
    "Presion_Arterial",
    "FC",
    "fr",
    "peso",
    "talla",
    "circunferencia",
    "Ninguno_factor",
    "Hiperlipidemia_factor",
    "Diabetes_factor",
    "Hipertensión_facator",
    "Alcoholismo_factor",
    "Tabaquismo_factor",
    "Enfermedad_renal",
    "Hiperuricemia_factor",
    "Obesidad_factor",
    "Previo_factor",
    "ectasia_factor",
    "Cardiomio",
    "multivaso_factor",
    "Resvascularizacion_factor",
    "Padre_antecedente",
    "Madre_antecedente",
    "Abuelo_Materno_antecedente",
    "Abuelo_Paterno_antecedente",
    "Abuela_Materna_antecedente",
    "Abuela_Paterna_antecedente",
    "Hermano_antecedente",
    "Hermana_antecedente",
    "Prima_Materna_antecedente",
    "Prima_Paterna_antecedente",
    "Primo_Paterno_antecedente",
    "Primo_Materno_antecedente",
    "Tia_Materna_antecedente",
    "Tia_Paterna_antecedente",
    "Tia_Materno_antecedente",
    "Tia_Paterno_antecedente",
    "Inicio_sintomas",
    "Caracteristica_dolor",
    "Inicio_triage",
    "Termino_triage",
    "Dolor_Retroesternal",
    "Opresivo",
    "Irradiación_brazo_izquierdo",
    "Más_de_10_minutos",
    "Náuseas",
    "Diaforesis_1",
    "Síncope_1",
    "Dolor_Epigastrio",
    "Punzante",
    "Pleurítico",
    "Disnea",
    "Palpitación",
    "Diaforesis_2",
    "Síncope_2",
    "int_dolor",
    "Electrocardiograma",
    "local_electro",
    "ConSin_elevancion",
    "mace",
    "Kill_kimbal",
    "ck",
    "ck_mb",
    "Troponinas",
    "Glucosa",
    "Urea",
    "Creatinina",
    "Colesterol",
    "Trigliceridos",
    "Acido_Urico",
    "hb_glucosilada",
    "Proteinas",
    "LDL",
    "HDL",
    "Fibrinolisis",
    "Inicio_txfibronilis",
    "finaliza_txfibronilis",
    "Tipo_Fibrinolisis",
    "procedimiento_exitoso_1",
    "Inicio_Angio",
    "Tipo_Procedimiento",
    "sitio_puncion",
    "Lesiones_coronarias",
    "Coronaria_Derecha",
    "Coronaria_Izquierda",
    "Descendente_Anterior",
    "Descendente_Posterior",
    "Tronco_Coronario_Izquierdo",
    "Bifurcacion",
    "Circunfleja",
    "Dominancia_Derecha",
    "Codominancia",
    "Dominancia_Izquierda",
    "Ramo_Posterolateral",
    "Ramo_Septales",
    "Ramo_Marginales",
    "duqu",
    "Medin",
    "clasificacion_ac",
    "TIMI",
    "Procedimiento_TIM",
    "Calificacion_TIM",
    "Tomografia_coherenci",
    "Trombosis_intr",
    "Aspiracion_tromb",
    "Protesis_metalico",
    "protesis_num",
    "revascularizacion",
    "Procedimiento_exitoso_2",
    "AIRBUS",
    "Resu_AIRBUS",
    "Prote_Endovascular",
    "1_generacion",
    "2da_generacion",
    "Litotricia",
    "Schockwave",
    "Schockwave_compli",
    "Marcapasos",
    "Soporte_ventricular",
    "Complicaciones",
    "disfu_ventri",
    "compli_mecanicas",
    "compli_Pericarditis",
    "compli_Electricas",
    "Gamma",
    "gamma_cardi",
    "Localizacion_gamma",
    "Segmento_gamma",
    "Resonancia_inicial",
    "resultado_resonancia",
    "ergometria",
    "Etapa_1",
    "Etapa_2",
    "Etapa_3",
    "Etapa_4",
    "Etapa_5",
    "Etapa_6",
    "Etapa_7",
    "Suspension_estudio",
    "Distolico_inicial",
    "Sistolico_inicial",
    "eyeccion_ventriizqui",
    "movilidad_inicial",
    "Segmento",
    "Causa_defun",
    "Defuncion_fecha"
];
verificarRepetidas(palabras);
